print("this is 1st commit")
print("this is 2nd commit")
print("this is 3rd commit")
print("this is 1st commit of the NewBranch")
print("this is 2nd commit of the NewBranch")
print("this is 3rd commit of the NewBranch")
